version: '3.9'

networks:
  pg-network:
    driver: bridge

services:
  # ----------------------------------------------------------------
  # MINIO
  # ----------------------------------------------------------------
  minio_1:
    image: bitnami/minio:2023.6.23
    container_name: mt_hrm_minio_1
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${APP_ENV_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${APP_ENV_MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

  # ----------------------------------------------------------------
  # REDIS
  # ----------------------------------------------------------------  
  redis_1:
    image: bitnami/redis:6.2.12
    container_name: mt_hrm_redis_1
    ports:
      - 6300:6379
    environment:
      - REDIS_PASSWORD=${APP_ENV_REDIS_PASSWORD}
    volumes:
      - redis_data:/bitnami/redis/data

  # ----------------------------------------------------------------
  # REDIS SOCKET
  # ----------------------------------------------------------------  
  redis_io:
    image: bitnami/redis:6.2.12
    container_name: mt_hrm_redis_io
    ports:
      - 6301:6379
    environment:
      - REDIS_PASSWORD=${APP_ENV_REDIS_IO_CLUSTER_PASSWORD}

  # ----------------------------------------------------------------
  # POSTGRES 0
  # ----------------------------------------------------------------  
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${APP_ENV_POSTGRES_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${APP_ENV_POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${APP_ENV_POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${APP_ENV_POSTGRES_DATABASE}
      - REPMGR_USERNAME=${APP_ENV_REPMGR_USERNAME}
      - REPMGR_PASSWORD=${APP_ENV_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    restart: always

  # ----------------------------------------------------------------
  # POSTGRES 1
  # ----------------------------------------------------------------  
  pg-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${APP_ENV_POSTGRES_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${APP_ENV_POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${APP_ENV_POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${APP_ENV_POSTGRES_DATABASE}
      - REPMGR_USERNAME=${APP_ENV_REPMGR_USERNAME}
      - REPMGR_PASSWORD=${APP_ENV_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    restart: always

  # ----------------------------------------------------------------
  # POSTGRES 2
  # ----------------------------------------------------------------  
  pg-2:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - pg_2_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${APP_ENV_POSTGRES_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${APP_ENV_POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${APP_ENV_POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${APP_ENV_POSTGRES_DATABASE}
      - REPMGR_USERNAME=${APP_ENV_REPMGR_USERNAME}
      - REPMGR_PASSWORD=${APP_ENV_REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    restart: always

  # ----------------------------------------------------------------
  # PGPOOL
  # ----------------------------------------------------------------  
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 5400:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=${APP_ENV_REPMGR_USERNAME}
      - PGPOOL_SR_CHECK_PASSWORD=${APP_ENV_REPMGR_PASSWORD}
      - PGPOOL_POSTGRES_USERNAME=${APP_ENV_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${APP_ENV_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${APP_ENV_PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${APP_ENV_PGPOOL_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - pg-0
      - pg-1
      - pg-2

volumes:
  minio_data:
  redis_data:
  pg_0_data:
  pg_1_data:
  pg_2_data:
