version: '3.9'

services:
  # ----------------------------------------------------------------
  # MINIO
  # ----------------------------------------------------------------
  minio_1:
    image: bitnami/minio:2023.6.23
    container_name: mt_hrm_minio_1
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=${APP_ENV_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${APP_ENV_MINIO_ROOT_PASSWORD}
    volumes:
      - /data/mt_hrm/minio_data:/data
      - /opt/docker/mt_hrm/services/minio_1:/mt_hrm_minio_1_data
      - /etc/localtime:/etc/localtime:ro
